name: awslabs-prometheus
image: mcp/prometheus-mcp-server
type: server
meta:
  category: monitoring
  tags:
    - prometheus-mcp-server
    - monitoring
about:
  title: AWS Managed Prometheus
  description: Prometheus-compatible operations.
  icon: https://avatars.githubusercontent.com/u/3299148?v=4
source:
  project: https://github.com/awslabs/mcp
  commit: 76ec6993aec4c6281e5250cbeba8db6a5863f2ff
  directory: src/prometheus-mcp-server
