name: netlify
type: remote
dynamic:
  tools: true
meta:
  category: devops
  tags:
    - devops
    - hosting
    - deployment
    - remote
about:
  title: Netlify
  description: Software Development
  icon: https://www.google.com/s2/favicons?domain=netlify.com&sz=64
remote:
  transport_type: sse
  url: https://mcp.netlify.com/sse
oauth:
  - provider: netlify
    secret: netlify.personal_access_token
    env: NETLIFY_PERSONAL_ACCESS_TOKEN
